application:
  host: '0.0.0.0'
database:
  require_ssl: true
email_client:
  base_url: "https://api.resend.com"
  sender_email: "dedy.prasetyo.h@gmail.com"
  authorization_token: "re_dDGU6vLA_7NwFXBnpVBK4xkpTNpPeXYKi"